version: '3.8'
services:
  db:
    # 公式のイメージを利用(M1チップ用)
    image: arm64v8/mysql:8.0
    # IntelチップのMacでは以下のimageを指定する
    # image: mysql:8.0

    # コンテナの名前を設定
    container_name: graphql-sns-db

    # ローカルPCの3307番ポートとDockerコンテナの3306番ポートを接続する
    ports:
      - 3307:3306

    # DBに設定する値
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: graphql-sns-db
      MYSQL_PASSWORD: root
      TZ: 'Asia/Tokyo'

    # DBのデータをvolumeに移しデータを永続化する
    volumes:
      - graphql-sns-volume:/var/lib/mysql

    # 利用するDockerNetworkを指定
    networks:
      - graphql-sns-nw

# Docker上で本コンテナが設置されるNetworkを作成
networks:
  graphql-sns-nw:
# MySQLに保存したデータを永続化する場所
volumes:
  graphql-sns-volume:
